stryker/Metadata/unpackaged/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Studentsss__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipName>Studentsss</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Studentsss</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studentsss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Samsung/force-app/main/default/classes/std.cls
public class std {
    public static void AfterupdateNoOfStudents(list<Studentsss__c> lstStudentsss){
        
        list<id>ids=new list<id>();
        list<Studentsss__c> stdnew=trigger.new;
        list<Studentsss__c> stdold=trigger.old;
        for(Studentsss__c stdobj:lstStudentsss){
            //if(stdnew.class__c!=stdold.class__c){
                ids.add(stdobj.id);
            }
        }
    }