stryker/Metadata/unpackaged/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Students__c</fullName>
        <label>No Of Students</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Studentsss__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipName>Studentsss</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Studentsss</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studentsss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Manifest_project/force-app/main/default/classes/CorrectExistingNoOfStundentsinClass.cls
public class CorrectExistingNoOfStundentsinClass implements Database.Batchable<sObject>  {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        //String query = 'SELECT Id,Class__c FROM Studentsss__c WHERE ID =\'a0X0o00000NEkbg\'';
        String query = 'SELECT Id,Class__c FROM Studentsss__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Studentsss__c> records){
        set<Id> setClassId = new set<Id> ();
        for(Studentsss__c objst: records){
            if(objst.Class__c != NULL){
                setClassId.add(objst.Class__c);
            }           
        }
        System.debug('setClassId==> '+setClassId);
        if(!setClassId.isEmpty()){
            list<Class__c> lstClass = new list<Class__c> ();
            for(Class__c objCls:[Select id,(Select ID FROM Studentsss__r) from Class__c WHERE ID IN :setClassId]){
                System.debug('objCls==> '+objCls);
                System.debug('objCls.Studentsss__r '+objCls.Studentsss__r);
                System.debug('objCls.Studentsss__r '+objCls.Studentsss__r.size());
                if(objCls.Studentsss__r != NULL && !objCls.Studentsss__r.isEmpty()){
                    Class__c cls = new Class__c();
                    cls.No_Of_Students__c = objCls.Studentsss__r.size();
                    cls.Id = objCls.Id;
                    lstClass.add(cls);
                }
            }
            System.debug('lstClass ==> '+lstClass);
            if(!lstClass.isEmpty()){
                update lstClass;
            }                     
        }
        
    }    
    
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }  
    
}