stryker/Metadata/unpackaged/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Studentsss__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipName>Studentsss</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Studentsss</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studentsss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gitProject/force-app/main/default/classes/StudentTestCls.cls
@isTest
public class StudentTestCls {
    //Meaning the creating the test data
    @testSetup 
    static void createStudent() {
        Class__c cls = new Class__c();
        cls.Name='chandu';
        insert cls;
        
        Class__c cls1 = new Class__c();
        cls1.Name='chandu1';
        insert cls1;
      
        Studentsss__c std=new Studentsss__c();
        std.Class__c=cls.id;
        std.Name__c='siva';
        insert std;
    }
    
    @istest
    static void updateStudent(){
        Studentsss__c stu = [select id,Class__c from Studentsss__c LIMIT 1]; 
        Class__c cls1 = [select id from Class__c where Name ='chandu1' LIMIT 1];
        stu.Class__c = cls1.Id;
        update stu;
        
        
    }
    @istest
    static void deleteStudent(){
             Studentsss__c stu = [select id,Class__c from Studentsss__c LIMIT 1]; 
        delete stu;
    }
    
    
    

}