stryker/Metadata/unpackaged/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Con_Child_Party_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Con Child Party Role</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Sales_Hirachy__c.object
<CustomObject>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Party_Role__c</fullName>
        <label>Child Party Role</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_Role__c</fullName>
        <label>Party Role</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Hirachys</relationshipLabel>
        <relationshipName>Sales_Hirachys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Hirachy</label>
    <nameField>
        <label>Sales Hirachy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hirachys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/classes/connectionhandler.cls
public class connectionhandler {
    public static void updatesales(list<connection__c> conlist){
        list<id>conids=new list<id>();
        for(Connection__c conobj:conlist){
            if(conobj.Con_Child_Party_Role__c!=null){
                conids.add(conobj.Con_Child_Party_Role__c);
                system.debug('conids===>'+conids);
            }
        }
        if(!conids.isEmpty()){
            list<Sales_Hirachy__c> saleslist=new list<Sales_Hirachy__c>();
            for(Account acc:[select id,(select id,Child_Party_Role__c,Party_Role__c,check__c from Sales_Hirachys__r
                                        where check__c=false) from Account where id In:conids]){
                                            system.debug('acc===>'+acc);
                                                if(acc.Sales_Hirachys__r != NULL && !acc.Sales_Hirachys__r.isEmpty()){
                                                    for(Sales_Hirachy__c aobj:acc.Sales_Hirachys__r){
                                                    system.debug('aobj===>'+aobj);
                                                    aobj.check__c=true;
                                                    aobj.Party_Role__c=acc.Id;
                                                    saleslist.add(aobj);
                                                    system.debug('saleslist===>'+saleslist);
                                                }
                                            }
                                            
                                        }
            if(!saleslist.isEmpty()){
                update saleslist; 
            }
        }
    }
    
}