stryker/Metadata/unpackaged/objects/Customer__c.object
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Aplied_Ammount__c</fullName>
        <label>Aplied Ammount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan</relationshipLabel>
        <relationshipName>Loan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_date__c</fullName>
        <label>Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Emi__c</fullName>
        <label>Emi</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sactioned_Amount__c</fullName>
        <label>Sactioned Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>balance_Amount__c</fullName>
        <label>balance Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/classes/shedule_pro.cls
public class shedule_pro implements Schedulable {
    public void execute(SchedulableContext oc){
       /* list<Loan__c>Loanlist=[select id,customer__r.email__c,Emi__c,Sactioned_Amount__c,
                               Aplied_Ammount__c,balance_Amount__c from loan__c];
        list<Id>ids=new list<id>();
        for(loan__c l:loanlist){
            ids.add(l.customer__c);
        }*/
        list<loan__c>mylist=[select id,customer__r.email__c,Emi__c,Sactioned_Amount__c,balance_Amount__c,
                            Due_date__c from loan__c where balance_Amount__c>0];
        list<string>mails=new list<string>();
         list<Messaging.Email> sendmails=new list<Messaging.Email>();
        for(Loan__c ln:mylist){
                mails.add(ln.customer__r.email__c);
       // }
       // for(loan__c l:mylist){
        messaging.SingleEmailMessage msg=new messaging.SingleEmailMessage();
        msg.setToAddresses(mails);
        string body='Dear Customer <br/>';
            body=body+'Ammount of Rs.'+ln.Emi__c+'Will be deducted from your Account on'+ln.Due_date__c+'<br/>';
            body=body+'please kepp Sufficient Balence in The Account to Provide Late fee Charges';
        msg.setHtmlBody(body);
        msg.setSubject('loan');
        sendmails.add(msg);
       }
        messaging.sendEmail(sendmails);
    }
}