stryker/Metadata/unpackaged/objects/Employe__c.object
<CustomObject>
    <fields>
        <fullName>Employ_Id__c</fullName>
        <label>Employ Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_salary__c</fullName>
        <label>Total salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Employe</label>
    <nameField>
        <label>Employe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Salary__c.object
<CustomObject>
    <fields>
        <fullName>Basic_Salary__c</fullName>
        <label>Basic Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employ_Id__c</fullName>
        <label>Employ Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HRA__c</fullName>
        <label>HRA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Allowance__c</fullName>
        <label>Other Allowance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Salary</label>
    <nameField>
        <label>Salary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Manifest_project/force-app/main/default/classes/SalaryTestclass.cls
@isTest
public class SalaryTestclass {
    @isTest
    static void testme(){
        Employe__c emp=new Employe__c();
        emp.Name='ravi';
        emp.Employ_Id__c='S123';
        insert emp;
        Salary__c sal=new Salary__c();
        sal.Basic_Salary__c=200;
        sal.HRA__c=300;
        sal.Other_Allowance__c=500;
        sal.Employ_Id__c='S123';
        insert sal;
        Salary__c sl=[select id,Basic_Salary__c,Employ_Id__c,HRA__c,Other_Allowance__c from Salary__c];
        sl.Basic_Salary__c=100;
        //sl.HRA__c=200;
        //sl.Other_Allowance__c=400;
        update sl;
        Employe__c empl=[select id,Employ_Id__c,Total_salary__c from Employe__c where Employ_Id__c=:sl.Employ_Id__c];
        system.assertEquals(900,empl.Total_salary__c);
    }
    
}