stryker/Metadata/unpackaged/objects/Employe__c.object
<CustomObject>
    <fields>
        <fullName>Employ_Id__c</fullName>
        <label>Employ Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_salary__c</fullName>
        <label>Total salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Employe</label>
    <nameField>
        <label>Employe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/Metadata/unpackaged/objects/Salary__c.object
<CustomObject>
    <fields>
        <fullName>Basic_Salary__c</fullName>
        <label>Basic Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employ_Id__c</fullName>
        <label>Employ Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HRA__c</fullName>
        <label>HRA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Allowance__c</fullName>
        <label>Other Allowance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Salary</label>
    <nameField>
        <label>Salary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/force-app/main/default/classes/SalaryTrigger.cls
public class SalaryTrigger {
    public static void UpdateTotSalary(Map<Id,Salary__c>Oldmap,Map<Id,Salary__c>Newmap){
        list<string>Empids=new list<string>();
        for(Salary__c salobj:Oldmap.values()){
            if(Oldmap.get(salobj.id).Basic_Salary__c!=Newmap.get(salobj.id).Basic_Salary__c ||
               Oldmap.get(salobj.id).HRA__c!=Newmap.get(salobj.id).HRA__c ||
               Oldmap.get(salobj.id).Other_Allowance__c!=Newmap.get(salobj.id).Other_Allowance__c){
                   Empids.add(salobj.Employ_Id__c);
               }
        }
        if(!Empids.isEmpty()){
            list<Employe__c>emplist=new list<Employe__c>();
            for(Employe__c empobj:[select id,Employ_Id__c,Total_salary__c from Employe__c where Employ_Id__c IN:Empids]){
                for(Salary__c salobj:Newmap.values()){
                    empobj.Total_salary__c=salobj.Basic_Salary__c+salobj.HRA__c+salobj.Other_Allowance__c;
                    emplist.add(empobj);
                }
            }
            if(!emplist.isEmpty()){
                update emplist;
            }
        }
    }
}