stryker/Metadata/unpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>first_name__c</fullName>
        <label>first name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_name__c</fullName>
        <label>last name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>``</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

stryker/force-app/main/default/classes/ProTestclass.cls
@istest
public class ProTestclass {
	@testSetup
    static void testdata(){
       project__c pp=new project__c();
        pp.first_name__c='venu';
        pp.last_name__c='k';
        pp.phone__c='12345';
        insert pp;
        project_app_wrap w=new project_app_wrap();
         w.flag=false;
         w.ap=pp;
    }
    @istest
    static void testgo(){
        project_app pr=new project_app();
        pr.go();
        pr.next();
    }
}